sudo: required
services:
  - docker

before_install:
  - docker build -t otonye -f Dockerfile.dev .

script:
  - docker run -e CI=true otonye npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-696893447737"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret-access_key:
    secure: "$AWS_SECRET_KEY"

